name: deploy_backend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Add remote origin
        run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/webrtc-next-demo.git

      - name: Deploy backend to heroku
        run: git push --force heroku `git subtree split --prefix packages/backend HEAD`:refs/heads/master
